notifications:
  slack: wtsi-cgpit:ptUMR1tkNyZJYd9TpGoss8WR
  email: false

sudo: false

cache:
  directories:
  - $HOME/.cache/bower

language: node_js

node_js:
 - node

install:
  - npm install -g eslint eslint-plugin-react babel-eslint bower phantomjs-prebuilt
  - pip install --user RangeHTTPServer
  - bower install

before_script:
  - python -m RangeHTTPServer &

script:
  - timeout 180 phantomjs test/run-jasmine.js http://localhost:8000/test/

after_script:
  - eslint js
